title: UVA CS 3130 Student Notes
description: Notes from CSO 2 with Reiss, Fall 2024
theme: just-the-docs

url: https://ameimeilia.github.io

baseurl: "/cso2-notes"

nav_enabled: true

math: katex

callouts:
  highlight:
    color: purple